### PR TITLE
Completed Profile Functionality #8

### PR DESCRIPTION
**Pull request by fatin123**
User story 6. Tasks 7 and 8.
Once a profile is created, it can be viewed by any user at /profiles/username
Clicking on the username of the forum post's author brings you to the professor's profile page.

### CODE REVIEW

**Review by gamecoder95 — APPROVED** [review]
Looks great, lots of functionality added, good work!

**Review by cynthiac3 — APPROVED** [review]
Awesome, that's a lot of useful new functionalities!

**Comment by tash2cool** [comment]
Great work!!! Everything works perfectly!

**Review by tash2cool — APPROVED** [review]
Great work!! Everything works perfectly!!

**Pull request merged**
