### PR TITLE
Added student selection feature to select specific teacher survey

### PR DESCRIPTION
**Pull request by Chasiwpaw**
User Story #5 task 3

### CODE REVIEW

**Review by gamecoder95 — CHANGES_REQUESTED** [review]
Please rename "renderThisShit" to something more appropriate lol.

**Comment by Chasiwpaw** [comment]
Thanks for pointing that out haha

**Review by gamecoder95 — APPROVED** [review]
Much better! 👍

**Comment by compgirl123** [comment]
Looks amazing Andrew😀

**Pull request merged**
